#!/usr/bin/env python3
"""
Helper script to set up .env file for Market Activity Prediction Agent.
"""

import os
import secrets
from pathlib import Path

def create_env_file():
    """Create or update .env file with required settings."""
    env_path = Path(".env")
    example_path = Path(".env.example")
    
    print("Market Activity Prediction Agent - Environment Setup")
    print("=" * 60)
    
    # Check if .env already exists
    if env_path.exists():
        print("\n⚠️  .env file already exists!")
        response = input("Do you want to create a backup and create a new one? (y/n): ")
        if response.lower() == 'y':
            backup_path = Path(".env.backup")
            if backup_path.exists():
                backup_path.unlink()
            env_path.rename(backup_path)
            print(f"✓ Backed up existing .env to .env.backup")
        else:
            print("Keeping existing .env file. Exiting.")
            return
    
    # Generate secret key
    secret_key = secrets.token_urlsafe(32)
    
    # Get user input
    print("\nPlease provide the following information:")
    print("(Press Enter to use defaults)")
    
    bigquery_project = input("\nBigQuery Project ID: ").strip()
    bigquery_dataset = input("BigQuery Dataset name [market_data]: ").strip() or "market_data"
    secret_key_input = input(f"Secret Key [auto-generated]: ").strip() or secret_key
    
    # Create .env content
    env_content = f"""# Market Activity Prediction Agent - Environment Configuration
# Generated by setup_env.py

# ============================================
# REQUIRED SETTINGS
# ============================================

# Secret key for JWT authentication
SECRET_KEY={secret_key_input}

# BigQuery Configuration
BIGQUERY_PROJECT_ID={bigquery_project}
BIGQUERY_DATASET={bigquery_dataset}

# Optional: Path to Google Cloud service account JSON file
# GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account-key.json

# ============================================
# OPTIONAL SETTINGS (defaults shown)
# ============================================

# API Settings
API_HOST=0.0.0.0
API_PORT=8000
API_RATE_LIMIT=100/minute
CACHE_TTL_SECONDS=60

# Redis Configuration (optional)
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_DB=0

# JWT Authentication
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30

# Model Parameters
VOLATILITY_LOOKBACK_DAYS=30
EVENT_CORRELATION_WINDOW=90
CONFIDENCE_THRESHOLD=0.70
ALERT_VOLATILITY_THRESHOLD=1.5

# Model Training
MODEL_RETRAIN_FREQUENCY_DAYS=7
MIN_TRAINING_SAMPLES=100

# Prediction Settings
DEFAULT_FORECAST_HORIZON_DAYS=5
MAX_FORECAST_HORIZON_DAYS=30

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json

# Twilio (optional - for SMS alerts)
# TWILIO_ACCOUNT_SID=your-twilio-account-sid
# TWILIO_AUTH_TOKEN=your-twilio-auth-token
# TWILIO_PHONE_NUMBER=+1234567890
"""
    
    # Write .env file
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"\n✓ Created .env file")
    print(f"\nNext steps:")
    print(f"1. Review and edit .env if needed")
    print(f"2. Run: python3.12 run.py")
    print(f"\nNote: Extra variables from other projects in .env will be ignored.")

if __name__ == "__main__":
    create_env_file()

